language: go
go: 
  - 1.19.x

install:
  - go get github.com/gohugoio/hugo

script: 
  - mkdir themes
  - cd themes
  - git submodule add https://github.com/halogenica/beautifulhugo.git beautifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  GitHub_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
